- hosts: kube-master  #定义的主机组，即应用的主机
  gather_facts: no
  remote_user: root     # 远程用户为root

  tasks:
    - name: mkdir yaml
      shell: mkdir -p /opt/yaml

    - name: ceph transfer
      copy:
        src: "/opt/ceph-secret.yaml"
        dest: "/opt/yaml/"