- hosts: kube-all  #定义的主机组，即应用的主机
  gather_facts: no
  remote_user: root     # 远程用户为root

  tasks:
    - name: stop firewall
      shell: systemctl stop firewalld.service

    - name: disable firewall
      shell: systemctl disable firewalld.service
