- hosts: kube-all  #定义的主机组，即应用的主机
  gather_facts: no
  remote_user: root     # 远程用户为root

  tasks:
    - name: ntp transfer
      copy:
          src: "&&pkgurl/ntp"
          dest: "/tmp/"

    - name: localtime
      shell: mv /etc/localtime /etc/localtime.bak

    - name: ls localtime
      shell: ln -s /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime

    - name: hwclock
      shell: hwclock --hctosys

    - name: save clock
      shell: clock -w

    - name: ntp rpm
      shell: rpm -ivh /tmp/ntp/rpm/* --nodeps --force
 
    - name: ntp config
      shell: cp /tmp/ntp/ntp1.conf /etc/ntp.conf

    - name: enable ntp
      shell: systemctl enable ntpd

    - name: restart ntp
      shell: systemctl restart ntpd