- hosts: kube-nfs  #定义的主机组，即应用的主机
  gather_facts: no
  remote_user: root     # 远程用户为root

  tasks:
    - name: firewall cmd transfer
      copy:
          src: "&&pkgurl/shell/firewall_nfs.sh"
          dest: "/tmp/"
 
    - name: chmod sh
      shell: chmod +x /tmp/firewall_nfs.sh

    - name: config firewall
      shell: /tmp/firewall_nfs.sh
