- hosts: kube-all  #定义的主机组，即应用的主机
  gather_facts: no
  remote_user: root     # 远程用户为root

  tasks:
    - name: ntp transfer
      copy:
          src: "&&pkgurl/shell/ntp.sh"
          dest: "/tmp/"
 
    - name: ntp chmod +x
      shell: chmod +x /tmp/ntp.sh

    - name: install ntp
      shell: /tmp/ntp.sh
