- hosts: kube-ceph  #定义的主机组，即应用的主机
  gather_facts: no
  remote_user: root     # 远程用户为root

  tasks:
    - name: ceph transfer
      copy:
          src: "&&pkgurl/ceph"
          dest: "/opt/"

    - name: chmod sh
      shell: chmod +x /opt/ceph/*.sh

    - name: install ceph
      shell: /opt/ceph/ceph.sh