- hosts: kube-ceph-deploy  #定义的主机组，即应用的主机
  gather_facts: no
  remote_user: root     # 远程用户为root

  tasks:
    - name: ansible transfer
      copy:
        src: "&&pkgurl/ansible"
        dest: "/tmp/"

    - name: ansible config
      copy:
        src: "/etc/ansible/hosts"
        dest: "/tmp/"

    - name: install ansible
      shell: rpm -ivh /tmp/ansible/*.rpm --force --nodeps

    - name: config ansible
      shell: cat /tmp/hosts > /etc/ansible/hosts

    - name: config no check
      shell: sed -i "s/#host_key_checking/host_key_checking/g" /etc/ansible/ansible.cfg

    - name: chmod sh
      shell: chmod +x /opt/ceph/ceph_deploy.sh

    - name: deploy ceph
      shell: /opt/ceph/ceph_deploy.sh

